version: '2'
services:
    nexus:
        restart: always
        image: ${NEXUS_IMG_TAG}
        hostname: nexus
        container_name: nexus
        environment:
            - TZ=Asia/Shanghai
            - JAVA_MAX_HEAP=1200m
            - JAVA_MIN_HEAP=1200m
        volumes:
            - ./data/:/nexus-data/:z
        ports:
            - 8081:8081
